create table audit_events (
    id bigint generated by default as identity primary key,
    tenant_id varchar(255) not null,
    organization_name varchar(255) not null,
    actor varchar(255) not null,
    action varchar(255) not null,
    target varchar(255) not null,
    details varchar(1400) not null,
    created_at timestamp with time zone not null
);

create table deployments (
    id bigint generated by default as identity primary key,
    tenant_id varchar(255) not null,
    organization_name varchar(255) not null,
    deployment_key varchar(255) not null,
    service_name varchar(255) not null,
    owner_team varchar(255) not null,
    environment varchar(255) not null,
    commit_sha varchar(255) not null,
    pull_request_title varchar(500) not null,
    created_at timestamp with time zone not null,
    status varchar(255) not null,
    score integer not null,
    risk_level varchar(255),
    recommendation varchar(1000),
    ai_explanation varchar(1600),
    assessed_at timestamp with time zone
);

create table deployment_dependencies (
    deployment_id bigint not null,
    sort_order integer not null,
    dependency_name varchar(255),
    primary key (deployment_id, sort_order),
    constraint fk_deployment_dependencies_deployment foreign key (deployment_id) references deployments(id)
);

create table deployment_signals (
    deployment_id bigint not null,
    sort_order integer not null,
    signal_type varchar(255) not null,
    title varchar(255) not null,
    description varchar(800) not null,
    risk_weight integer not null,
    primary key (deployment_id, sort_order),
    constraint fk_deployment_signals_deployment foreign key (deployment_id) references deployments(id)
);

create table deployment_risk_reasons (
    deployment_id bigint not null,
    sort_order integer not null,
    category varchar(255) not null,
    evidence varchar(1000) not null,
    impact integer not null,
    primary key (deployment_id, sort_order),
    constraint fk_deployment_risk_reasons_deployment foreign key (deployment_id) references deployments(id)
);

create table engineering_events (
    id bigint generated by default as identity primary key,
    tenant_id varchar(255) not null,
    organization_name varchar(255) not null,
    service_name varchar(255) not null,
    owner_team varchar(255) not null,
    event_type varchar(255) not null,
    title varchar(255) not null,
    details varchar(1400) not null,
    deployment_key varchar(255),
    commit_sha varchar(255),
    occurred_at timestamp with time zone not null
);

create table memory_links (
    id bigint generated by default as identity primary key,
    tenant_id varchar(255) not null,
    organization_name varchar(255) not null,
    deployment_id bigint not null,
    engineering_event_id bigint not null,
    pattern_type varchar(255) not null,
    reason varchar(1000) not null,
    confidence integer not null,
    created_at timestamp with time zone not null,
    constraint fk_memory_links_engineering_event foreign key (engineering_event_id) references engineering_events(id)
);

create table pull_request_reviews (
    id bigint generated by default as identity primary key,
    tenant_id varchar(255) not null,
    organization_name varchar(255) not null,
    repository varchar(255) not null,
    pr_number integer not null,
    title varchar(500) not null,
    author varchar(255) not null,
    service_name varchar(255) not null,
    owner_team varchar(255) not null,
    ci_status varchar(255) not null,
    linked_deployment_id bigint,
    risk_score integer not null,
    recommendation varchar(255) not null,
    explanation varchar(1600) not null,
    decision varchar(255),
    decision_note varchar(1000),
    created_at timestamp with time zone not null
);

create table pull_request_changed_files (
    pull_request_review_id bigint not null,
    sort_order integer not null,
    changed_file varchar(255),
    primary key (pull_request_review_id, sort_order),
    constraint fk_pull_request_changed_files_review foreign key (pull_request_review_id) references pull_request_reviews(id)
);

create table integration_connections (
    id bigint generated by default as identity primary key,
    tenant_id varchar(255) not null,
    organization_name varchar(255) not null,
    provider varchar(255) not null,
    status varchar(255) not null,
    display_name varchar(255) not null,
    install_url varchar(255) not null,
    scopes varchar(255) not null,
    token_secret_ref varchar(255) not null,
    external_account varchar(255),
    connected_at timestamp with time zone,
    last_sync_at timestamp with time zone,
    last_sync_status varchar(255) not null,
    health_score integer not null,
    status_detail varchar(1000) not null
);

create table integration_sync_events (
    id bigint generated by default as identity primary key,
    tenant_id varchar(255) not null,
    organization_name varchar(255) not null,
    integration_connection_id bigint not null,
    provider varchar(255) not null,
    status varchar(255) not null,
    records_inspected integer not null,
    latency_ms integer not null,
    health_score integer not null,
    detail varchar(1000) not null,
    created_at timestamp with time zone not null
);

create table integration_token_secrets (
    id bigint generated by default as identity primary key,
    secret_ref varchar(255) not null unique,
    tenant_id varchar(255) not null,
    provider varchar(255) not null,
    encrypted_access_token varchar(4096) not null,
    encrypted_refresh_token varchar(4096),
    token_fingerprint varchar(255) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table incidents (
    id bigint generated by default as identity primary key,
    tenant_id varchar(255) not null,
    organization_name varchar(255) not null,
    incident_key varchar(255) not null unique,
    deployment_id bigint not null,
    deployment_key varchar(255) not null,
    service_name varchar(255) not null,
    owner_team varchar(255) not null,
    environment varchar(255) not null,
    severity varchar(255) not null,
    status varchar(255) not null,
    risk_score integer not null,
    summary varchar(700) not null,
    affected_systems varchar(1000) not null,
    commander_brief varchar(1000) not null,
    recommended_action varchar(1000) not null,
    opened_at timestamp with time zone not null,
    updated_at timestamp with time zone,
    resolved_at timestamp with time zone
);

create table incident_timeline_events (
    incident_id bigint not null,
    sort_order integer not null,
    occurred_at timestamp with time zone not null,
    actor varchar(255) not null,
    label varchar(255) not null,
    detail varchar(1000) not null,
    primary key (incident_id, sort_order),
    constraint fk_incident_timeline_events_incident foreign key (incident_id) references incidents(id)
);

create table architecture_services (
    id bigint generated by default as identity primary key,
    tenant_id varchar(255) not null,
    organization_name varchar(255) not null,
    service_name varchar(255) not null,
    owner_team varchar(255) not null,
    runtime varchar(255) not null,
    tier varchar(255) not null,
    repository varchar(255) not null,
    description varchar(1000) not null
);

create table architecture_dependencies (
    id bigint generated by default as identity primary key,
    tenant_id varchar(255) not null,
    organization_name varchar(255) not null,
    source_service varchar(255) not null,
    target_service varchar(255) not null,
    dependency_type varchar(255) not null,
    criticality varchar(255) not null,
    notes varchar(1000) not null
);

create table architecture_risks (
    id bigint generated by default as identity primary key,
    tenant_id varchar(255) not null,
    organization_name varchar(255) not null,
    service_name varchar(255) not null,
    risk_type varchar(255) not null,
    severity varchar(255) not null,
    explanation varchar(1200) not null,
    recommendation varchar(1200) not null
);

create table service_profiles (
    id bigint generated by default as identity primary key,
    tenant_id varchar(255) not null,
    organization_name varchar(255) not null,
    service_name varchar(255) not null,
    owner_team varchar(255) not null,
    production_criticality varchar(255) not null,
    last_seen_at timestamp with time zone not null
);

create table service_profile_dependencies (
    service_profile_id bigint not null,
    sort_order integer not null,
    dependency_name varchar(255),
    primary key (service_profile_id, sort_order),
    constraint fk_service_profile_dependencies_profile foreign key (service_profile_id) references service_profiles(id)
);

create index idx_audit_events_tenant_created_at on audit_events(tenant_id, created_at);
create index idx_deployments_tenant_created_at on deployments(tenant_id, created_at);
create index idx_deployments_tenant_key on deployments(tenant_id, deployment_key);
create index idx_engineering_events_tenant_service on engineering_events(tenant_id, service_name);
create index idx_memory_links_tenant_deployment on memory_links(tenant_id, deployment_id);
create index idx_pull_request_reviews_tenant_created_at on pull_request_reviews(tenant_id, created_at);
create index idx_integration_connections_tenant_provider on integration_connections(tenant_id, provider);
create index idx_integration_sync_events_tenant_created_at on integration_sync_events(tenant_id, created_at);
create index idx_incidents_tenant_status on incidents(tenant_id, status);
create index idx_architecture_services_tenant_service on architecture_services(tenant_id, service_name);
create index idx_architecture_dependencies_tenant_target on architecture_dependencies(tenant_id, target_service);
