create table background_jobs (
    id bigint generated by default as identity primary key,
    tenant_id varchar(255) not null,
    organization_name varchar(255) not null,
    job_type varchar(255) not null,
    status varchar(255) not null,
    target_type varchar(255) not null,
    target_id bigint not null,
    target_label varchar(255) not null,
    payload varchar(1200) not null,
    attempts integer not null,
    max_attempts integer not null,
    next_run_at timestamp with time zone not null,
    last_error varchar(1200),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    completed_at timestamp with time zone
);

create index idx_background_jobs_due on background_jobs(status, next_run_at);
create index idx_background_jobs_tenant_created_at on background_jobs(tenant_id, created_at);
create index idx_background_jobs_tenant_status on background_jobs(tenant_id, status);
