create table webhook_deliveries (
    id bigint generated by default as identity primary key,
    tenant_id varchar(255) not null,
    organization_name varchar(255) not null,
    provider varchar(255) not null,
    external_delivery_id varchar(255) not null,
    event_type varchar(255) not null,
    status varchar(255) not null,
    payload varchar(6000) not null,
    request_id varchar(255) not null,
    failure_reason varchar(1200),
    target_reference varchar(255),
    replay_attempts integer not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    processed_at timestamp with time zone,
    last_replayed_at timestamp with time zone
);

create index idx_webhook_deliveries_tenant_created_at on webhook_deliveries(tenant_id, created_at);
create index idx_webhook_deliveries_tenant_status on webhook_deliveries(tenant_id, status);
create index idx_webhook_deliveries_external_delivery on webhook_deliveries(provider, external_delivery_id);
