create table users (
    id bigint generated by default as identity primary key,
    tenant_id varchar(255) not null,
    organization_name varchar(255) not null,
    email varchar(255) not null,
    password_hash varchar(255) not null,
    role varchar(255) not null,
    failed_login_attempts integer not null,
    locked_until timestamp with time zone,
    created_at timestamp with time zone not null,
    last_login_at timestamp with time zone,
    constraint uq_users_email unique (email)
);

insert into users (tenant_id, organization_name, email, password_hash, role, failed_login_attempts, created_at) values
    ('sentinel-demo', 'Sentinel Demo', 'admin@sentinel.ai', '$2b$10$lHgVRCEx.ouq3KwvDstB0eGfAbfqP0rYXJeXI.qqenw8QA4dbNeEq', 'ADMIN', 0, current_timestamp),
    ('sentinel-demo', 'Sentinel Demo', 'release@sentinel.ai', '$2b$10$2A2L6FjnE0Z8zvXouJT63e2EavHymlqHTqw3Sfies7tKtFz89cLSG', 'RELEASE_MANAGER', 0, current_timestamp),
    ('sentinel-demo', 'Sentinel Demo', 'viewer@sentinel.ai', '$2b$10$UCWtTzq1O3x8PFKAU5q5XOZ8BPccn220DK5e2Swwsl5uL2Zwckyj2', 'VIEWER', 0, current_timestamp),
    ('acme-payments', 'Acme Payments', 'acme-release@sentinel.ai', '$2b$10$nxmRZiMiqNmAkcFqTII.VewaMTDcclBoOY/qE6FnKsFbO/IjwB4Hi', 'RELEASE_MANAGER', 0, current_timestamp);
