create table ai_usage_events (
    id bigint generated by default as identity primary key,
    tenant_id varchar(255) not null,
    organization_name varchar(255) not null,
    operation varchar(255) not null,
    model varchar(255) not null,
    input_tokens integer not null,
    output_tokens integer not null,
    latency_ms bigint not null,
    estimated_cost_usd numeric(12, 6) not null,
    succeeded boolean not null,
    created_at timestamp with time zone not null
);

create index idx_ai_usage_events_tenant_created_at on ai_usage_events(tenant_id, created_at);
