create table error_events (
    id bigint generated by default as identity primary key,
    tenant_id varchar(255) not null,
    organization_name varchar(255) not null,
    error_type varchar(255) not null,
    message varchar(1000),
    path varchar(500),
    http_method varchar(16),
    request_id varchar(255),
    occurred_at timestamp with time zone not null
);

create index idx_error_events_tenant_occurred_at on error_events(tenant_id, occurred_at);
